### PR TITLE
model and controls reconfigured for elsa_x

### LINKED ISSUE #255: Gazebo Model for new robot
For the new robot, we'll need to have a gazebo model. Some general designs may be found in the #mech slack channel. Note that because the name of the new robot has not yet been decided on, we should name things in such a way that a "Find and Replace" can easily change over everything later.

### PR DESCRIPTION
**Pull request by ValRat**
closes #255

### CODE REVIEW

**Comment by garethellis0** [comment]
Taking a quick glance, this looks good to me, but I'll need my desktop to test it, which I may not have for a few days at least. I'll ask @RobynCastro to take a look and make sure it works for him. Am I correct in assuming this is basically the configs for `jfrost` copied and slightly modified? Also, could you post some photos here of what the new model looks like?

**Comment by ValRat** [comment]
Picture of model:

screenshot from 2018-05-02 15-00-20

screenshot from 2018-05-02 15-00-52

**Comment by RobynCastro** [comment]
Looks like it works to me! I've added a back view of the robot showing the lidar in action.
elsagazebo

**Comment by garethellis0** [comment]
Pretty much looks good to me, only thing I might mention is that I think the wheels will be significantly larger. For reference, here are a few photos from the grabcad:
screenshot from 2018-05-02 21-35-29
screenshot from 2018-05-02 21-34-21

**Comment by garethellis0** [comment]
Another note, we should make sure that all the topics line up with those indicated in #306

**Comment by ValRat** [comment]
Ah, I didn't see that folder, will make appropriate changes

**Comment by ValRat** [comment]
Robot preview: 
screenshot from 2018-05-02 22-32-24
screenshot from 2018-05-02 22-31-54

**Comment by garethellis0** [comment]
Looks good to me, but I'd like @RobynCastro to take one last run of it (since I can't without my desktop rn) and approve it if everything looks good to him.

**Comment by ValRat** [comment]
Currently investigating a model drifting issue...

**Comment by garethellis0** [comment]
Drift issue? Could you post a GIF? Off the top of my head I would try lifting it up and dropping it once, and seeing if the issue persists, or checking the friction coefficients on the wheels and casters (casters should have almost none, wheels should have a fair amount)

**Comment by ValRat** [comment]
Hard to gif it, I think we had this behaviour with the old model as well. As it stands, I'm OK with the current behaviour (works better with a controller compared to running `keyboard_teleop`).

**Comment by ValRat** [comment]
I take back what I said, changing `mu` does the trick.

**Pull request merged**
